/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import DAO.DangNhapDAO;
import DAO.ConnectionDB;
import DAO.NhanVienDAO;
import POJO.TrungGian;
import java.awt.geom.RoundRectangle2D;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author Admin
 */
public class DangKy extends javax.swing.JFrame {      
    /**
     * Creates new form DangNhap
     */
    public DangKy() {
        //this.setLocationRelativeTo(null); //set cho form nằm giữa
        initComponents();
        setTitle("Đăng Nhập");
        setLocationRelativeTo(null); // this method display the JFrame to center position of a screen
        //bo tròn viền
        setShape(new RoundRectangle2D.Double(0 , 0, getWidth(), getHeight(), 50 ,50));
        
        dateNgaySinh.setDateFormatString("yyyy-MM-dd");

    }
    
    public String getMaNVLastInsert()
    {
        String manv = "";
        ConnectionDB conn = new ConnectionDB();
        conn.getCn();
        String sql = "select TOP 1 MANV from NHANVIEN ORDER BY MANV DESC";
        ResultSet rs = conn.executeQuery(sql);
        try {
            while (rs.next()) 
            {
                manv = rs.getString(1);
            }
        }  
            catch(Exception e)
            {
                System.out.println(e);
            }
        return manv;
    }
    public int kiemTraTaiKhoanTonTai(String taikhoan)
    {
        int check = 0;
        ConnectionDB conn = new ConnectionDB();
        conn.getCn();
        String sql = "SELECT COUNT(TAIKHOAN) AS DEM FROM NHANVIEN WHERE TAIKHOAN = '"+taikhoan+"'";
        ResultSet rs = conn.executeQuery(sql);
        try {
            while (rs.next()) 
            {
                check = rs.getInt(1);
            }
        }  
            catch(Exception e)
            {
                System.out.println(e);
            }
        return check;
    }
    
    public void dangKyTaiKhoan()
    {
        ConnectionDB conn = new ConnectionDB();
        conn.getCn();
        
        String strManv = getMaNVLastInsert().substring(2).trim(); //lấy mấy số sau mã nv ra
        int so = Integer.parseInt(strManv) + 1; //tăng mã lên 1
        String socuoi = String.format("%03d", so).trim();
        String manv = "NV"+socuoi.trim(); //vd NV002
        
        String gioitinh = "Nam";
        if(rdoNu.isSelected())
        {
            gioitinh = "Nữ";
        }
        else 
        {
            gioitinh = "Nam";
        }
        String ngaysinh = ((JTextField)dateNgaySinh.getDateEditor().getUiComponent()).getText();
        
        if(kiemTraTaiKhoanTonTai(txtTk.getText().trim()) == 0)
        {
            if(txtMk.getText().trim().equals(txtRmk.getText().trim())) //kt mat khau co giog nhau k
            {
                try
                {
                    String lenhsql = "insert into NhanVien(MaNV, TenNV, GioiTinh, NgaySinh,  DiaChi, SDT, TaiKhoan, MatKhau, Quyen, Avatar) " +
                    "values ('"+manv+"', N'"+txtHoTen.getText()+"', N'"+gioitinh.trim()+"', N'"+ngaysinh+"'"
                    + ", N'"+txtDiaChi.getText()+"', '"+txtSDT.getText()+"','"+txtTk.getText()+"',"
                    + " '"+txtMk.getText()+"', N'NHÂN VIÊN', 'avatarnull.png')";
                    int kq=NhanVienDAO.ThemXoaSuaNhanVien(lenhsql);
                    if(kq!=-1)
                    {
                        JOptionPane.showMessageDialog(this, "Đăng ký tài khoản thành công!", "Thông báo", 1);
                        DangNhap f = new DangNhap();
                        f.setVisible(true);
                        f.setLocationRelativeTo(null);
                        this.dispose();
                    }
                    else
                    JOptionPane.showMessageDialog(this, "Mã nhân viên này đã tồn tại, không thể thêm", "Thông báo", 2);
                }
                catch(Exception e)
                {
                    System.out.println(e);
                }
            }
            else
            {
                JOptionPane.showMessageDialog(this, "Mật khẩu không khớp!", "Thông báo", 2);
            }
        }
        else
        {
            JOptionPane.showMessageDialog(this, "Tài khoản đã tồn tại!", "Thông báo", 2);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        panel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnSignup = new CUSTOMBUTTON.Button();
        btnClose = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        txtHoTen = new CUSTOMBUTTON.MyTextField();
        txtMk = new CUSTOMBUTTON.MyTextField();
        txtTk = new CUSTOMBUTTON.MyTextField();
        txtRmk = new CUSTOMBUTTON.MyTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        rdoNam = new javax.swing.JRadioButton();
        rdoNu = new javax.swing.JRadioButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        dateNgaySinh = new com.toedter.calendar.JDateChooser();
        txtSDT = new CUSTOMBUTTON.MyTextField();
        txtDiaChi = new CUSTOMBUTTON.MyTextField();
        lbDangKy = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel2.setBackground(new java.awt.Color(22, 116, 66));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/bg_login.jpg"))); // NOI18N

        panel.setBackground(new java.awt.Color(255, 255, 255));
        panel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setBackground(new java.awt.Color(61, 168, 82));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(61, 168, 82));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Đăng Ký");

        btnSignup.setBackground(new java.awt.Color(61, 168, 82));
        btnSignup.setForeground(new java.awt.Color(255, 255, 255));
        btnSignup.setText("ĐĂNG KÝ");
        btnSignup.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnSignup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSignupActionPerformed(evt);
            }
        });

        btnClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/close2.png"))); // NOI18N
        btnClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCloseMouseClicked(evt);
            }
        });

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        txtHoTen.setText("Họ và tên");
        txtHoTen.setPrefixIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/name-24.png"))); // NOI18N
        txtHoTen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtHoTenMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtHoTenMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtHoTenMouseExited(evt);
            }
        });

        txtMk.setText("Mật khẩu");
        txtMk.setPrefixIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/password.png"))); // NOI18N
        txtMk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtMkMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtMkMouseExited(evt);
            }
        });

        txtTk.setText("Tài khoản");
        txtTk.setPrefixIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/account.png"))); // NOI18N
        txtTk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtTkMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtTkMouseExited(evt);
            }
        });
        txtTk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTkActionPerformed(evt);
            }
        });

        txtRmk.setText("Nhập lại mật khẩu");
        txtRmk.setPrefixIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/password.png"))); // NOI18N
        txtRmk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtRmkMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtRmkMouseExited(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(230, 245, 241));

        jLabel4.setForeground(new java.awt.Color(122, 140, 141));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/gender-24.png"))); // NOI18N
        jLabel4.setText("GIới tính");

        buttonGroup1.add(rdoNam);
        rdoNam.setForeground(new java.awt.Color(122, 140, 141));
        rdoNam.setText("Nam");

        buttonGroup1.add(rdoNu);
        rdoNu.setForeground(new java.awt.Color(122, 140, 141));
        rdoNu.setText("Nữ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(31, 31, 31)
                .addComponent(rdoNam)
                .addGap(33, 33, 33)
                .addComponent(rdoNu)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(rdoNam)
                    .addComponent(rdoNu))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(230, 245, 241));

        jLabel5.setForeground(new java.awt.Color(122, 140, 141));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/date-20.png"))); // NOI18N
        jLabel5.setText(" Ngày sinh");

        dateNgaySinh.setBackground(new java.awt.Color(230, 245, 241));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(dateNgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(10, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dateNgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        txtSDT.setText("Số điện thoại");
        txtSDT.setPrefixIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/phone-20.png"))); // NOI18N
        txtSDT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtSDTMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtSDTMouseExited(evt);
            }
        });

        txtDiaChi.setText("Địa chỉ");
        txtDiaChi.setPrefixIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/address-20.png"))); // NOI18N
        txtDiaChi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtDiaChiMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtDiaChiMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txtDiaChi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtSDT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtRmk, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtMk, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtTk, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtHoTen, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(txtHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(txtTk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(txtMk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(txtRmk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(txtSDT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(txtDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
        );

        lbDangKy.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbDangKy.setForeground(new java.awt.Color(61, 168, 82));
        lbDangKy.setText("Đăng nhập ngay");
        lbDangKy.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbDangKy.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbDangKyMouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Đã có tài khoản?");

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addComponent(btnClose)
                .addGap(15, 15, 15))
            .addGroup(panelLayout.createSequentialGroup()
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelLayout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelLayout.createSequentialGroup()
                        .addGap(132, 132, 132)
                        .addComponent(btnSignup, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelLayout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbDangKy)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLayout.createSequentialGroup()
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(btnClose)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSignup, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lbDangKy))
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 407, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSignupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSignupActionPerformed
        // TODO add your handling code here:
        dangKyTaiKhoan();
    }//GEN-LAST:event_btnSignupActionPerformed

    private void txtHoTenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtHoTenMouseClicked
        // TODO add your handling code here:
        txtHoTen.setText("");
    }//GEN-LAST:event_txtHoTenMouseClicked

    private void btnCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCloseMouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnCloseMouseClicked

    private void lbDangKyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbDangKyMouseClicked
        // TODO add your handling code here:
        DangNhap f = new DangNhap();
        f.setVisible(true);
        f.setLocationRelativeTo(null);
        this.dispose();
        
    }//GEN-LAST:event_lbDangKyMouseClicked

    private void txtTkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtTkMouseClicked
        // TODO add your handling code here:
        txtTk.setText("");
    }//GEN-LAST:event_txtTkMouseClicked

    private void txtDiaChiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtDiaChiMouseClicked
        // TODO add your handling code here:
        txtDiaChi.setText("");
    }//GEN-LAST:event_txtDiaChiMouseClicked

    private void txtSDTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtSDTMouseClicked
        // TODO add your handling code here:
        txtSDT.setText("");
    }//GEN-LAST:event_txtSDTMouseClicked

    private void txtRmkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtRmkMouseClicked
        // TODO add your handling code here:
        txtRmk.setText("");
    }//GEN-LAST:event_txtRmkMouseClicked

    private void txtMkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtMkMouseClicked
        // TODO add your handling code here:
        txtMk.setText("");
    }//GEN-LAST:event_txtMkMouseClicked

    private void txtTkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTkActionPerformed
        // TODO add your handling code here:
        txtTk.setText("");
    }//GEN-LAST:event_txtTkActionPerformed

    private void txtHoTenMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtHoTenMouseExited
        // TODO add your handling code here:
        if(txtHoTen.getText().trim().equals(""))
        {
            txtHoTen.setText("Họ và tên");
        }
    }//GEN-LAST:event_txtHoTenMouseExited

    private void txtTkMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtTkMouseExited
        // TODO add your handling code here:
        if(txtTk.getText().trim().equals(""))
        {
            txtTk.setText("Tài khoản");
        }
    }//GEN-LAST:event_txtTkMouseExited

    private void txtMkMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtMkMouseExited
        // TODO add your handling code here:
        if(txtMk.getText().trim().equals(""))
        {
            txtMk.setText("Mật khẩu");
        }
    }//GEN-LAST:event_txtMkMouseExited

    private void txtRmkMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtRmkMouseExited
        // TODO add your handling code here:
        if(txtRmk.getText().trim().equals(""))
        {
            txtRmk.setText("Nhập lại mật khẩu");
        }
    }//GEN-LAST:event_txtRmkMouseExited

    private void txtSDTMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtSDTMouseExited
        // TODO add your handling code here:
        if(txtSDT.getText().trim().equals(""))
        {
            txtSDT.setText("Số điện thoại");
        }
    }//GEN-LAST:event_txtSDTMouseExited

    private void txtDiaChiMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtDiaChiMouseExited
        // TODO add your handling code here:
        if(txtDiaChi.getText().trim().equals(""))
        {
            txtDiaChi.setText("Địa chỉ");
        }
    }//GEN-LAST:event_txtDiaChiMouseExited

    private void txtHoTenMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtHoTenMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHoTenMouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DangKy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DangKy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DangKy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DangKy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DangKy().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnClose;
    private CUSTOMBUTTON.Button btnSignup;
    private javax.swing.ButtonGroup buttonGroup1;
    private com.toedter.calendar.JDateChooser dateNgaySinh;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel lbDangKy;
    private javax.swing.JPanel panel;
    private javax.swing.JRadioButton rdoNam;
    private javax.swing.JRadioButton rdoNu;
    private CUSTOMBUTTON.MyTextField txtDiaChi;
    private CUSTOMBUTTON.MyTextField txtHoTen;
    private CUSTOMBUTTON.MyTextField txtMk;
    private CUSTOMBUTTON.MyTextField txtRmk;
    private CUSTOMBUTTON.MyTextField txtSDT;
    private CUSTOMBUTTON.MyTextField txtTk;
    // End of variables declaration//GEN-END:variables
}
