/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import MDI.QLNhanVien;
import MDI.QLKhachHang;
import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import MDI.CheckPhong;
import MDI.QLDichVu;
import MDI.QLHoaDon;
import MDI.QLPhieuDatPhong;
import MDI.QLPhong;
import MDI.ThongKe;
import POJO.TrungGian;
import java.awt.Cursor;
import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author GreenDuy
 */
public class MainForm extends javax.swing.JFrame {
    /**
     * Creates new form MainForm
     */
    public MainForm() {
        initComponents();
        setLocationRelativeTo(null); // this method display the JFrame to center position of a screen
        setExtendedState(MAXIMIZED_BOTH);
        
        troNhanVien.setVisible(false);
        troKhachHang.setVisible(false);
        troPhong.setVisible(false);
        troCheckPhong.setVisible(false);
        troDichVu.setVisible(false);
        troHoaDon.setVisible(false);
        troThongKe.setVisible(false);
        troDatPhong.setVisible(false);
        
        String avatar = TrungGian.getAvatar();
        String quyen = TrungGian.getQuyen();

        
        ImageIcon icon = new ImageIcon(getClass().getResource("/Image/" + avatar));
        Image img = icon.getImage().getScaledInstance(60, 60, Image.SCALE_SMOOTH);
        lbName.setIcon(new ImageIcon(img));
        
        lbName.setText("Xin chào, " + TrungGian.getTenNV());
        //set cursor hand for button
        setCursorHandForButton();
        Desktop.removeAll();
        Desktop.updateUI();
        CheckPhong f = new CheckPhong();
        Desktop.add(f);
        f.setSize(1920, 1080);
        f.setVisible(true);
        
        if(quyen.equals("NHÂN VIÊN"))
        {
            btnNhanVien.setVisible(false);
        }
    }
    public final void setCursorHandForButton()
    {
//        10 button
        btnNhanVien.setCursor(new Cursor(Cursor.HAND_CURSOR));
        btnKhachHang.setCursor(new Cursor(Cursor.HAND_CURSOR));
        btnPhong.setCursor(new Cursor(Cursor.HAND_CURSOR));
        btnCheckPhong.setCursor(new Cursor(Cursor.HAND_CURSOR));
        btnPhong.setCursor(new Cursor(Cursor.HAND_CURSOR));
        btnDichVu.setCursor(new Cursor(Cursor.HAND_CURSOR));
        btnHoaDon.setCursor(new Cursor(Cursor.HAND_CURSOR));
        btnThongKe.setCursor(new Cursor(Cursor.HAND_CURSOR));
        btnDatPhong.setCursor(new Cursor(Cursor.HAND_CURSOR));
        btnThoat.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    void setColor(JPanel panel)
    {
        panel.setBackground(new Color(80, 200, 120));
    }
    void resetColor(JPanel panel)
    {
        panel.setBackground(new Color(0,168,107));
    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        connectionDB1 = new DAO.ConnectionDB();
        bg = new javax.swing.JPanel();
        sidepanel = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        btnPhong = new CUSTOM.PanelRound();
        icPhong = new javax.swing.JLabel();
        lbPhong = new javax.swing.JLabel();
        troPhong = new javax.swing.JLabel();
        btnKhachHang = new CUSTOM.PanelRound();
        jLabel9 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        troKhachHang = new javax.swing.JLabel();
        btnNhanVien = new CUSTOM.PanelRound();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        troNhanVien = new javax.swing.JLabel();
        btnThoat = new CUSTOM.PanelRound();
        jLabel21 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        btnHoaDon = new CUSTOM.PanelRound();
        jLabel10 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        troHoaDon = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnThongKe = new CUSTOM.PanelRound();
        lbThongke = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        troThongKe = new javax.swing.JLabel();
        btnDichVu = new CUSTOM.PanelRound();
        jLabel12 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        troDichVu = new javax.swing.JLabel();
        btnCheckPhong = new CUSTOM.PanelRound();
        jLabel13 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        troCheckPhong = new javax.swing.JLabel();
        btnDatPhong = new CUSTOM.PanelRound();
        lbThongke1 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        troDatPhong = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lbName = new javax.swing.JLabel();
        lbAvatar = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        Desktop = new javax.swing.JDesktopPane();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("HomeStay");
        setLocationByPlatform(true);
        setMinimumSize(new java.awt.Dimension(500, 500));

        bg.setPreferredSize(new java.awt.Dimension(1434, 658));

        sidepanel.setBackground(new java.awt.Color(46, 139, 87));

        jSeparator1.setAlignmentX(4.0F);
        jSeparator1.setAlignmentY(4.0F);
        jSeparator1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jSeparator1.setPreferredSize(new java.awt.Dimension(50, 30));

        jLabel2.setFont(new java.awt.Font("Bauhaus 93", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("GREENHOME");
        jLabel2.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        btnPhong.setBackground(new java.awt.Color(0, 168, 107));
        btnPhong.setPreferredSize(new java.awt.Dimension(160, 54));
        btnPhong.setRoundBottomLeft(20);
        btnPhong.setRoundBottomRight(20);
        btnPhong.setRoundTopLeft(20);
        btnPhong.setRoundTopRight(20);
        btnPhong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPhongMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnPhongMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnPhongMouseExited(evt);
            }
        });
        btnPhong.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        icPhong.setForeground(new java.awt.Color(255, 255, 255));
        icPhong.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        icPhong.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/home.png"))); // NOI18N
        btnPhong.add(icPhong, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, 40));

        lbPhong.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbPhong.setForeground(new java.awt.Color(255, 255, 255));
        lbPhong.setText("Phòng");
        btnPhong.add(lbPhong, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, 110, 20));

        troPhong.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/one-finger-24.png"))); // NOI18N
        btnPhong.add(troPhong, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, -1, -1));

        btnKhachHang.setBackground(new java.awt.Color(0, 168, 107));
        btnKhachHang.setPreferredSize(new java.awt.Dimension(160, 54));
        btnKhachHang.setRoundBottomLeft(20);
        btnKhachHang.setRoundBottomRight(20);
        btnKhachHang.setRoundTopLeft(20);
        btnKhachHang.setRoundTopRight(20);
        btnKhachHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnKhachHangMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnKhachHangMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnKhachHangMouseExited(evt);
            }
        });
        btnKhachHang.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Khách Hàng");
        btnKhachHang.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, 110, 20));

        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/customer.png"))); // NOI18N
        btnKhachHang.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, 40));

        troKhachHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/one-finger-24.png"))); // NOI18N
        btnKhachHang.add(troKhachHang, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, -1, -1));

        btnNhanVien.setBackground(new java.awt.Color(0, 168, 107));
        btnNhanVien.setPreferredSize(new java.awt.Dimension(160, 54));
        btnNhanVien.setRoundBottomLeft(20);
        btnNhanVien.setRoundBottomRight(20);
        btnNhanVien.setRoundTopLeft(20);
        btnNhanVien.setRoundTopRight(20);
        btnNhanVien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnNhanVienMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnNhanVienMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnNhanVienMouseExited(evt);
            }
        });
        btnNhanVien.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Nhân Viên");
        btnNhanVien.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, 110, 20));

        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/worker-24.png"))); // NOI18N
        btnNhanVien.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, 40));

        troNhanVien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/one-finger-24.png"))); // NOI18N
        btnNhanVien.add(troNhanVien, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, -1, -1));

        btnThoat.setBackground(new java.awt.Color(0, 168, 107));
        btnThoat.setPreferredSize(new java.awt.Dimension(160, 54));
        btnThoat.setRoundBottomLeft(20);
        btnThoat.setRoundBottomRight(20);
        btnThoat.setRoundTopLeft(20);
        btnThoat.setRoundTopRight(20);
        btnThoat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnThoatMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnThoatMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnThoatMouseExited(evt);
            }
        });
        btnThoat.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/exit.png"))); // NOI18N
        btnThoat.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, 40));

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Thoát");
        btnThoat.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 110, 20));

        btnHoaDon.setBackground(new java.awt.Color(0, 168, 107));
        btnHoaDon.setPreferredSize(new java.awt.Dimension(160, 54));
        btnHoaDon.setRoundBottomLeft(20);
        btnHoaDon.setRoundBottomRight(20);
        btnHoaDon.setRoundTopLeft(20);
        btnHoaDon.setRoundTopRight(20);
        btnHoaDon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnHoaDonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnHoaDonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnHoaDonMouseExited(evt);
            }
        });
        btnHoaDon.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Hoá Đơn");
        btnHoaDon.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, 110, 20));

        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/bill.png"))); // NOI18N
        btnHoaDon.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, 40));

        troHoaDon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/one-finger-24.png"))); // NOI18N
        btnHoaDon.add(troHoaDon, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/cabin.png"))); // NOI18N

        btnThongKe.setBackground(new java.awt.Color(0, 168, 107));
        btnThongKe.setPreferredSize(new java.awt.Dimension(160, 54));
        btnThongKe.setRoundBottomLeft(20);
        btnThongKe.setRoundBottomRight(20);
        btnThongKe.setRoundTopLeft(20);
        btnThongKe.setRoundTopRight(20);
        btnThongKe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnThongKeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnThongKeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnThongKeMouseExited(evt);
            }
        });
        btnThongKe.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbThongke.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbThongke.setForeground(new java.awt.Color(255, 255, 255));
        lbThongke.setText("Thống Kê ");
        btnThongKe.add(lbThongke, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, 90, 20));

        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/chart.png"))); // NOI18N
        btnThongKe.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, 40));

        troThongKe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/one-finger-24.png"))); // NOI18N
        btnThongKe.add(troThongKe, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, -1, -1));

        btnDichVu.setBackground(new java.awt.Color(0, 168, 107));
        btnDichVu.setPreferredSize(new java.awt.Dimension(160, 54));
        btnDichVu.setRoundBottomLeft(20);
        btnDichVu.setRoundBottomRight(20);
        btnDichVu.setRoundTopLeft(20);
        btnDichVu.setRoundTopRight(20);
        btnDichVu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDichVuMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnDichVuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnDichVuMouseExited(evt);
            }
        });
        btnDichVu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Dịch Vụ");
        btnDichVu.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, 110, 20));

        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/hamburger-24.png"))); // NOI18N
        btnDichVu.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, 40));

        troDichVu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/one-finger-24.png"))); // NOI18N
        btnDichVu.add(troDichVu, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, -1, -1));

        btnCheckPhong.setBackground(new java.awt.Color(0, 168, 107));
        btnCheckPhong.setPreferredSize(new java.awt.Dimension(160, 54));
        btnCheckPhong.setRoundBottomLeft(20);
        btnCheckPhong.setRoundBottomRight(20);
        btnCheckPhong.setRoundTopLeft(20);
        btnCheckPhong.setRoundTopRight(20);
        btnCheckPhong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCheckPhongMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCheckPhongMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCheckPhongMouseExited(evt);
            }
        });
        btnCheckPhong.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Kiểm Tra Phòng");
        btnCheckPhong.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, 110, 20));

        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/hotel-24.png"))); // NOI18N
        btnCheckPhong.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, 40));

        troCheckPhong.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/one-finger-24.png"))); // NOI18N
        btnCheckPhong.add(troCheckPhong, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, -1, -1));

        btnDatPhong.setBackground(new java.awt.Color(0, 168, 107));
        btnDatPhong.setPreferredSize(new java.awt.Dimension(160, 54));
        btnDatPhong.setRoundBottomLeft(20);
        btnDatPhong.setRoundBottomRight(20);
        btnDatPhong.setRoundTopLeft(20);
        btnDatPhong.setRoundTopRight(20);
        btnDatPhong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDatPhongMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnDatPhongMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnDatPhongMouseExited(evt);
            }
        });
        btnDatPhong.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbThongke1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbThongke1.setForeground(new java.awt.Color(255, 255, 255));
        lbThongke1.setText("Đặt Phòng");
        btnDatPhong.add(lbThongke1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, 90, 20));

        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/ok-24.png"))); // NOI18N
        btnDatPhong.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, 40));

        troDatPhong.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/one-finger-24.png"))); // NOI18N
        btnDatPhong.add(troDatPhong, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, -1, -1));

        javax.swing.GroupLayout sidepanelLayout = new javax.swing.GroupLayout(sidepanel);
        sidepanel.setLayout(sidepanelLayout);
        sidepanelLayout.setHorizontalGroup(
            sidepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidepanelLayout.createSequentialGroup()
                .addGroup(sidepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(sidepanelLayout.createSequentialGroup()
                        .addGroup(sidepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(sidepanelLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(sidepanelLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(btnPhong, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(sidepanelLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(btnHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(sidepanelLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(btnThoat, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(sidepanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(btnThongKe, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(sidepanelLayout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(sidepanelLayout.createSequentialGroup()
                                .addGap(57, 57, 57)
                                .addComponent(jLabel1))
                            .addGroup(sidepanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(btnKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(sidepanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(sidepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnCheckPhong, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnDichVu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnDatPhong, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnNhanVien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        sidepanelLayout.setVerticalGroup(
            sidepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidepanelLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(btnCheckPhong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(btnNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(btnKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(btnPhong, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(btnDichVu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(btnDatPhong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(btnHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(btnThongKe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnThoat, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );

        jPanel2.setBackground(new java.awt.Color(46, 139, 87));

        lbName.setFont(new java.awt.Font("UTM Neo Sans Intel", 0, 16)); // NOI18N
        lbName.setForeground(new java.awt.Color(255, 255, 255));
        lbName.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lbName.setText("Name Staff");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(lbAvatar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(577, 577, 577)
                .addComponent(lbName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(20, 20, 20))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbAvatar)
                .addGap(8, 8, 8)
                .addComponent(lbName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(14, 14, 14))
        );

        Desktop.setBackground(new java.awt.Color(204, 204, 204));
        Desktop.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout DesktopLayout = new javax.swing.GroupLayout(Desktop);
        Desktop.setLayout(DesktopLayout);
        DesktopLayout.setHorizontalGroup(
            DesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1198, Short.MAX_VALUE)
        );
        DesktopLayout.setVerticalGroup(
            DesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 849, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Desktop)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Desktop)
                .addGap(27, 27, 27))
        );

        javax.swing.GroupLayout bgLayout = new javax.swing.GroupLayout(bg);
        bg.setLayout(bgLayout);
        bgLayout.setHorizontalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgLayout.createSequentialGroup()
                .addComponent(sidepanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        bgLayout.setVerticalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgLayout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(sidepanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jMenu3.setText("File");
        jMenuBar2.add(jMenu3);

        jMenu4.setText("Edit");
        jMenuBar2.add(jMenu4);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, 933, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNhanVienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNhanVienMouseClicked
        // TODO add your handling code here:
        troPhong.setVisible(false);
        troNhanVien.setVisible(true);
        troKhachHang.setVisible(false);
        troPhong.setVisible(false);
        troCheckPhong.setVisible(false);
        troDichVu.setVisible(false);
        troDatPhong.setVisible(false);
        troHoaDon.setVisible(false);
        troThongKe.setVisible(false);
        
        Desktop.removeAll();
        Desktop.updateUI();
        QLNhanVien f = new QLNhanVien();
        Desktop.add(f);
        f.setSize(Desktop.getSize());
        f.setVisible(true);
    }//GEN-LAST:event_btnNhanVienMouseClicked

    private void btnNhanVienMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNhanVienMouseEntered
        // TODO add your handling code here:
        setColor(btnNhanVien);
    }//GEN-LAST:event_btnNhanVienMouseEntered

    private void btnNhanVienMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNhanVienMouseExited
        // TODO add your handling code here:
        resetColor(btnNhanVien);
    }//GEN-LAST:event_btnNhanVienMouseExited

    private void btnKhachHangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnKhachHangMouseClicked
        // TODO add your handling code here:
        troPhong.setVisible(false);
        troNhanVien.setVisible(false);
        troKhachHang.setVisible(true);
        troPhong.setVisible(false);
        troCheckPhong.setVisible(false);
        troDichVu.setVisible(false);
        troHoaDon.setVisible(false);
        troThongKe.setVisible(false);
        troDatPhong.setVisible(false);
        
        Desktop.removeAll();
        Desktop.updateUI();
        QLKhachHang f = new QLKhachHang();
        Desktop.add(f);
        f.setSize(Desktop.getSize());
        f.setVisible(true);
    }//GEN-LAST:event_btnKhachHangMouseClicked

    private void btnKhachHangMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnKhachHangMouseEntered
        // TODO add your handling code here:
        setColor(btnKhachHang);
    }//GEN-LAST:event_btnKhachHangMouseEntered

    private void btnKhachHangMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnKhachHangMouseExited
        // TODO add your handling code here:
        resetColor(btnKhachHang);
    }//GEN-LAST:event_btnKhachHangMouseExited

    private void btnPhongMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPhongMouseClicked
        // TODO add your handling code here:
        troPhong.setVisible(true);
        troNhanVien.setVisible(false);
        troKhachHang.setVisible(false);
        troCheckPhong.setVisible(false);
        troDichVu.setVisible(false);
        troHoaDon.setVisible(false);
        troThongKe.setVisible(false);
        troDatPhong.setVisible(false);
        
        
        Desktop.removeAll();
        Desktop.updateUI();
        QLPhong f = new QLPhong();
        Desktop.add(f);
        f.setSize(Desktop.getSize());
        f.setVisible(true);
    }//GEN-LAST:event_btnPhongMouseClicked

    private void btnPhongMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPhongMouseEntered
        // TODO add your handling code here:
        setColor(btnPhong);
        
    }//GEN-LAST:event_btnPhongMouseEntered

    private void btnPhongMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPhongMouseExited
        // TODO add your handling code here:
        resetColor(btnPhong);
    }//GEN-LAST:event_btnPhongMouseExited

    private void btnThoatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnThoatMouseClicked
        // TODO add your handling code here:
        if(JOptionPane.showConfirmDialog(this, "Bạn có muốn thoát?","Thông báo",JOptionPane.YES_NO_OPTION)==JOptionPane.YES_OPTION) 
            System.exit(0);
    }//GEN-LAST:event_btnThoatMouseClicked

    private void btnThoatMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnThoatMouseEntered
        // TODO add your handling code here:
        setColor(btnThoat);
    }//GEN-LAST:event_btnThoatMouseEntered

    private void btnThoatMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnThoatMouseExited
        // TODO add your handling code here:
        resetColor(btnThoat);
    }//GEN-LAST:event_btnThoatMouseExited

    private void btnHoaDonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHoaDonMouseClicked
        // TODO add your handling code here:
        troPhong.setVisible(false);
        troNhanVien.setVisible(false);
        troKhachHang.setVisible(false);
        troCheckPhong.setVisible(false);
        troDichVu.setVisible(false);
        troHoaDon.setVisible(true);
        troThongKe.setVisible(false);
        troDatPhong.setVisible(false);
        
        Desktop.removeAll();
        Desktop.updateUI();
        QLHoaDon f = new QLHoaDon();
        Desktop.add(f);
        f.setSize(Desktop.getSize());
        f.setVisible(true);
    }//GEN-LAST:event_btnHoaDonMouseClicked

    private void btnHoaDonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHoaDonMouseEntered
        // TODO add your handling code here:
        setColor(btnHoaDon);
    }//GEN-LAST:event_btnHoaDonMouseEntered

    private void btnHoaDonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHoaDonMouseExited
        // TODO add your handling code here:
        resetColor(btnHoaDon);
    }//GEN-LAST:event_btnHoaDonMouseExited

    private void btnThongKeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnThongKeMouseClicked
        // TODO add your handling code here:
        troPhong.setVisible(false);
        troNhanVien.setVisible(false);
        troKhachHang.setVisible(false);
        troCheckPhong.setVisible(false);
        troDichVu.setVisible(false);
        troHoaDon.setVisible(false);
        troThongKe.setVisible(true);
        troDatPhong.setVisible(false);
        
        Desktop.removeAll();
        Desktop.updateUI();
        ThongKe f = new ThongKe();
        Desktop.add(f);
        f.setSize(Desktop.getSize());
        f.setVisible(true);
    }//GEN-LAST:event_btnThongKeMouseClicked

    private void btnThongKeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnThongKeMouseEntered
        // TODO add your handling code here:
        setColor(btnThongKe);
    }//GEN-LAST:event_btnThongKeMouseEntered

    private void btnThongKeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnThongKeMouseExited
        // TODO add your handling code here:
        resetColor(btnThongKe);
    }//GEN-LAST:event_btnThongKeMouseExited

    private void btnDichVuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDichVuMouseClicked
        // TODO add your handling code here:
        troPhong.setVisible(false);
        troNhanVien.setVisible(false);
        troKhachHang.setVisible(false);
        troCheckPhong.setVisible(false);
        troDichVu.setVisible(true);
        troHoaDon.setVisible(false);
        troThongKe.setVisible(false);
        troDatPhong.setVisible(false);
        
        Desktop.removeAll();
        Desktop.updateUI();
        QLDichVu f = new QLDichVu();
        Desktop.add(f);
        f.setSize(Desktop.getSize());
        f.setVisible(true);
    }//GEN-LAST:event_btnDichVuMouseClicked

    private void btnDichVuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDichVuMouseEntered
        // TODO add your handling code here:
        setColor(btnDichVu);
    }//GEN-LAST:event_btnDichVuMouseEntered

    private void btnDichVuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDichVuMouseExited
        // TODO add your handling code here:
        resetColor(btnDichVu);
    }//GEN-LAST:event_btnDichVuMouseExited

    private void btnCheckPhongMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCheckPhongMouseClicked
        // TODO add your handling code here:
        troPhong.setVisible(false);
        troNhanVien.setVisible(false);
        troKhachHang.setVisible(false);
        troCheckPhong.setVisible(true);
        troDichVu.setVisible(false);
        troHoaDon.setVisible(false);
        troThongKe.setVisible(false);
        troDatPhong.setVisible(false);
        
        Desktop.removeAll();
        Desktop.updateUI();
        CheckPhong f = new CheckPhong();
        Desktop.add(f);
        f.setSize(Desktop.getSize());
        f.setVisible(true);
        
        
    }//GEN-LAST:event_btnCheckPhongMouseClicked

    private void btnCheckPhongMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCheckPhongMouseEntered
        // TODO add your handling code here:
        setColor(btnCheckPhong);
    }//GEN-LAST:event_btnCheckPhongMouseEntered

    private void btnCheckPhongMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCheckPhongMouseExited
        // TODO add your handling code here:
        resetColor(btnCheckPhong);
    }//GEN-LAST:event_btnCheckPhongMouseExited

    private void btnDatPhongMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDatPhongMouseClicked
        // TODO add your handling code here:
        troPhong.setVisible(false);
        troNhanVien.setVisible(false);
        troKhachHang.setVisible(false);
        troCheckPhong.setVisible(false);
        troDichVu.setVisible(false);
        troHoaDon.setVisible(false);
        troThongKe.setVisible(false);
        troDatPhong.setVisible(true);
       
        Desktop.removeAll();
        Desktop.updateUI();
        QLPhieuDatPhong f = new QLPhieuDatPhong();
        Desktop.add(f);
        f.setSize(Desktop.getSize());
        f.setVisible(true);
    }//GEN-LAST:event_btnDatPhongMouseClicked

    private void btnDatPhongMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDatPhongMouseEntered
        // TODO add your handling code here:
        setColor(btnDatPhong);
    }//GEN-LAST:event_btnDatPhongMouseEntered

    private void btnDatPhongMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDatPhongMouseExited
        // TODO add your handling code here:
        resetColor(btnDatPhong);
    }//GEN-LAST:event_btnDatPhongMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane Desktop;
    private javax.swing.JPanel bg;
    private CUSTOM.PanelRound btnCheckPhong;
    private CUSTOM.PanelRound btnDatPhong;
    private CUSTOM.PanelRound btnDichVu;
    private CUSTOM.PanelRound btnHoaDon;
    private CUSTOM.PanelRound btnKhachHang;
    private CUSTOM.PanelRound btnNhanVien;
    private CUSTOM.PanelRound btnPhong;
    private CUSTOM.PanelRound btnThoat;
    private CUSTOM.PanelRound btnThongKe;
    private DAO.ConnectionDB connectionDB1;
    private javax.swing.JLabel icPhong;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lbAvatar;
    private javax.swing.JLabel lbName;
    private javax.swing.JLabel lbPhong;
    private javax.swing.JLabel lbThongke;
    private javax.swing.JLabel lbThongke1;
    private javax.swing.JPanel sidepanel;
    private javax.swing.JLabel troCheckPhong;
    private javax.swing.JLabel troDatPhong;
    private javax.swing.JLabel troDichVu;
    private javax.swing.JLabel troHoaDon;
    private javax.swing.JLabel troKhachHang;
    private javax.swing.JLabel troNhanVien;
    private javax.swing.JLabel troPhong;
    private javax.swing.JLabel troThongKe;
    // End of variables declaration//GEN-END:variables
}
